# Generated by Django 3.1.7 on 2022-07-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220722_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='p_name',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='projectName',
        ),
    ]
