# Generated by Django 3.1.7 on 2022-07-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220722_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='projectname',
        ),
    ]
