# Generated by Django 3.1.7 on 2022-07-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220725_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectname',
            new_name='name',
        ),
    ]
