# Generated by Django 3.2.14 on 2022-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220727_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='yil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.DateField(max_length=100)),
            ],
        ),
    ]
