# Generated by Django 3.2.14 on 2022-07-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_yil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yil',
        ),
        migrations.RenameField(
            model_name='completion',
            old_name='name',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='fractions',
            old_name='name',
            new_name='fraction',
        ),
        migrations.RenameField(
            model_name='operationtype',
            old_name='name',
            new_name='opType',
        ),
        migrations.RenameField(
            model_name='plannedyear',
            old_name='name',
            new_name='plannedyear',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state',
        ),
    ]
