# Generated by Django 3.2.14 on 2022-07-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220727_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completion',
            old_name='completion_date',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fractions',
            old_name='fraction',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationtype',
            old_name='opType',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plannedyear',
            old_name='plannedyear',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
    ]
