# Generated by Django 3.2.14 on 2022-07-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220727_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='function',
            new_name='name',
        ),
    ]
