# Generated by Django 3.2.14 on 2022-07-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_function_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.operationtype'),
        ),
    ]
