# Generated by Django 3.2.14 on 2022-07-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_project_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='operation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
