# Generated by Django 3.2.14 on 2022-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_project_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractions',
            name='name',
            field=models.IntegerField(max_length=100),
        ),
    ]
