# Generated by Django 3.2.14 on 2022-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_fractions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractions',
            name='name',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
