# Generated by Django 3.2.14 on 2022-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_fractions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
