# Generated by Django 3.2.14 on 2022-08-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_calc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calc',
        ),
    ]
