# Generated by Django 3.2.14 on 2022-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='perc',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
