# Generated by Django 3.2.14 on 2022-08-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220801_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='zorluk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.project'),
        ),
    ]
