# Generated by Django 3.2.14 on 2022-08-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_percentage_zorluk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percentage',
        ),
    ]
