# Generated by Django 3.2.14 on 2022-08-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zorluk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.project')),
            ],
        ),
    ]
