# Generated by Django 3.2.14 on 2022-08-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percentage',
        ),
    ]
