# Generated by Django 3.2.14 on 2022-08-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractions',
            name='name',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
