# Generated by Django 3.2.14 on 2022-08-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_fractions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.project')),
            ],
        ),
    ]
