# Generated by Django 3.2.14 on 2022-08-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_digi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digi',
        ),
    ]
