# Generated by Django 3.2.14 on 2022-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_project_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
