# Generated by Django 3.2.14 on 2022-08-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
