# Generated by Django 3.2.14 on 2022-08-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_delete_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
