# Generated by Django 3.2.14 on 2022-08-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_department_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='count',
        ),
    ]
