# Generated by Django 3.2.14 on 2022-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_department_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
