# Generated by Django 3.2.14 on 2022-08-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_responsible_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='short',
        ),
    ]
