# Generated by Django 3.2.14 on 2022-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_responsible_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Add function'),
        ),
    ]
