# Generated by Django 3.2.14 on 2022-08-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_project_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count',
        ),
    ]
