# Generated by Django 3.2.14 on 2022-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_project_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
