# Generated by Django 3.2.14 on 2022-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_project_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='count',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
