# Generated by Django 3.2.14 on 2022-08-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_department_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='count',
        ),
    ]
