# Generated by Django 3.2.14 on 2022-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_department_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short',
        ),
        migrations.AlterField(
            model_name='completion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Add Completion Date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Add Customer type'),
        ),
        migrations.AlterField(
            model_name='fractions',
            name='name',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Add Fraction'),
        ),
        migrations.AlterField(
            model_name='plannedyear',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Add Planned Year as MMMM-YY'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Project Name'),
        ),
    ]
