# Generated by Django 3.2.14 on 2022-08-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20220805_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='maturityCof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='digitalMaturity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity', models.CharField(blank=True, max_length=200, null=True)),
                ('coff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.maturitycof')),
            ],
        ),
    ]
