# Generated by Django 3.2.14 on 2022-08-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_digitalmaturity_maturitycof'),
    ]

    operations = [
        migrations.CreateModel(
            name='connectivityCof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(blank=True, max_length=200, null=True)),
                ('conn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.connectivitycof')),
            ],
        ),
    ]
