# Generated by Django 3.2.14 on 2022-08-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_connectivity_connectivitycof'),
    ]

    operations = [
        migrations.CreateModel(
            name='impCof',
            fields=[
                ('imp', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='impTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implemTime', models.CharField(blank=True, max_length=200, null=True)),
                ('imp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.impcof')),
            ],
        ),
    ]
