# Generated by Django 3.2.14 on 2022-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
