# Generated by Django 3.2.14 on 2022-08-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_department_resp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='Responsible',
        ),
    ]
