# Generated by Django 3.2.14 on 2022-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20220808_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
