# Generated by Django 3.2.14 on 2022-08-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_project_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count',
        ),
        migrations.AddField(
            model_name='project',
            name='conn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.connectivity'),
        ),
        migrations.AddField(
            model_name='project',
            name='digital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.digitalmaturity'),
        ),
        migrations.AddField(
            model_name='project',
            name='implem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.imptime'),
        ),
        migrations.AddField(
            model_name='project',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.item'),
        ),
    ]
