# Generated by Django 3.2.14 on 2022-08-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20220808_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.complexity'),
        ),
    ]
