# Generated by Django 3.2.14 on 2022-08-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id', '-dept']},
        ),
    ]
