# Generated by Django 3.2.14 on 2022-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20220811_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldstatus',
            name='project_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
