# Generated by Django 3.2.14 on 2022-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_oldstatus_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_a', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
