# Generated by Django 3.2.14 on 2022-08-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_project_item_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='smartMNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnfcoff', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='csorsmartmnf',
            name='mnf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.smartmnf'),
        ),
    ]
