# Generated by Django 3.2.14 on 2022-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20220815_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
