# Generated by Django 3.2.14 on 2022-08-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_project_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auto',
        ),
        migrations.AddField(
            model_name='oldstatus',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='impVar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.imptime', verbose_name='Implementation Time'),
        ),
    ]
