# Generated by Django 3.2.14 on 2022-08-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20220815_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='yes_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='itemA',
        ),
    ]
