# Generated by Django 3.2.14 on 2022-08-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20220817_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.yes_no'),
        ),
    ]
